picasso = Artist.create(name: "Pablo Picasso", birthyear: 1881, deathyear: 1973)
kusama = Artist.create(name: "Yayoi Kusama", birthyear: 1929, deathyear: nil)
malevich = Artist.create(name: "Kazimir Malevich", birthyear: 1879, deathyear: 1935)
van_gogh = Artist.create(name: "Vincent Van Gogh", birthyear: 1853, deathyear: 1890)
magritte = Artist.create(name: "Rene Magritte", birthyear: 1898, deathyear: 1967)
shiota = Artist.create(name: "Chiharu Shiota", birthyear: 1972, deathyear: nil)
cruz_diez = Artist.create(name: "Carlos Cruz Diez", birthyear: 1923, deathyear: nil)
hockney = Artist.create(name: "David Hockney", birthyear: 1937, deathyear: nil)
matisse = Artist.create(name: "Henri Matisse", birthyear: 1869, deathyear: 1954)
soto = Artist.create(name: "Jesus Soto", birthyear: 1923, deathyear: 2005)
wilson = Artist.create(name: "Richard Wilson", birthyear: 1953, deathyear: nil)
kapoor = Artist.create(name: "Anish Kapoor", birthyear: 1954, deathyear: nil)

# weeping_woman_img = "https://www.pablopicasso.org/images/paintings/the-weeping-woman.jpg"

the_weeping_woman = Artwork.create(name: "The Weeping Woman", artist: picasso, year: 1937, image_url: "https://www.pablopicasso.org/images/paintings/the-weeping-woman.jpg")
guernica = Artwork.create(name: "Guernica", artist: picasso, year: 1937, image_url: "https://upload.wikimedia.org/wikipedia/en/7/74/PicassoGuernica.jpg")
the_dream = Artwork.create(name: "The Dream", artist: picasso, year: 1932, image_url: "http://pictify.saatchigallery.com/files/works/pablo-picasso-women-asleep-in-an-armchair-the-dream-1932-1362336510_b.jpg")
black_square = Artwork.create(name: "Black Square", artist: malevich, year: 1914, image_url: "https://www.tate.org.uk/sites/default/files/styles/width-720/public/malevich5_0.jpg")
an_englishman_in_moscow = Artwork.create(name: "An Englishman in Moscow", artist: malevich, year: 1913, image_url: "https://www.tate.org.uk/sites/default/files/styles/width-720/public/images/036.jpg")
narcissus_garden = Artwork.create(name: "Narcissus Garden", artist: kusama, year: 1966, image_url: "https://artlogic-res.cloudinary.com/w_820,h_545,c_limit,f_auto,fl_lossy/ws-victoriamiro/usr/images/news/main_image/items/c1/c1644c37d1e444cf8f30e3225e26f3c9/screen-shot-2018-07-01-at-16.20.08.png")
sunflowers = Artwork.create(name: "Sunflowers", artist: van_gogh, year: 1888, image_url: "https://www.nationalgallery.org.uk/server.iip?FIF=/fronts/N-3863-00-000095-WZ-PYR.tif&CNT=1.0&WID=800&HEI=800&QLT=85&CVT=jpeg")
the_starry_night = Artwork.create(name: "The Starry Night", artist: van_gogh, year: 1889, image_url: "https://www.moma.org/learn/moma_learning/_assets/www.moma.org/wp/moma_learning/wp-content/uploads/2012/07/Van-Gogh.-Starry-Night-469x376.jpg")
me_somewhere_else = Artwork.create(name: "Me, Somwehere Else", artist: shiota, year: 2018, image_url: "https://s3-eu-west-1.amazonaws.com/blain/exhibitions/_lg/Chiharu-Shiota-Me-Somewhere-Else-2018-Installation-view-Courtesy-the-artist-and-BlainSouthern-Photo-Peter-Mallet-5.jpg")
chromosaturation = Artwork.create(name: "Chromosaturation", artist: cruz_diez, year: 1999, image_url: "https://scontent-amt2-1.cdninstagram.com/vp/bea253d412bc2af6ec3c16662df56b75/5CD2BCB0/t51.2885-15/sh0.08/e35/s640x640/28429857_155942491758160_6994989205206073344_n.jpg?_nc_ht=scontent-amt2-1.cdninstagram.com")
houston_penetrable = Artwork.create(name: "Houston Penetrable", artist: soto, year: 2014, image_url: "http://wonderfulvinyl.pvc.org/upload/WV20/The_Huoston_Penetrable_-_Photo_Museum_Fine_Arts_01.jpg")
all_the_eternal_love_i_have_for_the_pumpkins = Artwork.create(name: "All The Eternal Love I Have for the Pumpkins", artist: kusama, year: 2016, image_url: "https://dg19s6hp6ufoh.cloudfront.net/pictures/613013256/large/yayoi-kusama-victoria-miro-gallery-sculptures-paintings-mirror-rooms-designboom-07.jpeg?1464552395")
the_treachery_of_images = Artwork.create(name: "The Treachery of Images", artist: magritte, year: 1929, image_url: "http://www.rene-magritte.com/The%20Treachery%20of%20Images%20Rene%20Magritte.jpg")
the_snail = Artwork.create(name: "The Snail", artist: matisse, year: 1953, image_url: "https://www.tate.org.uk/art/images/work/T/T00/T00540_10.jpg")
twenty_fifty = Artwork.create(name: "20:50", artist: wilson, year: 1987, image_url: "https://carinawestling.files.wordpress.com/2011/12/img_3050.jpg")
sky_mirror_blue = Artwork.create(name: "Sky Mirror, Blue", artist: kapoor, year: 2016, image_url: "https://d33hx0a45ryfj1.cloudfront.net/additional/Dynamic/media/50fee232368d7918?w=1100&h=10000&crop=0")
portrait_of_an_artist = Artwork.create(name: "Portrait of an Artist (Pool with Two Figures)", artist: hockney, year: 1972, image_url: "https://www.christies.com/media-library/images/features/articles/2018/09/04/david-hockney-portrait-of-an-artist-pool-with-two-figures/davidhockneyb1937portraitofanartistpoolwithtwofigures19722400.jpg?width=383&quality=70")
a_bigger_splash = Artwork.create(name: "A Bigger Splash", artist: hockney, year: 1967, image_url: "https://www.tate.org.uk/art/images/work/T/T03/T03254_10.jpg")


puts "-------------------SEEDED---------------------------------"
